// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class AchievementConfig : IFlatbufferObject
{
public enum eCrypt : int
{
 code = 1392603177,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static AchievementConfig GetRootAsAchievementConfig(ByteBuffer _bb) { return GetRootAsAchievementConfig(_bb, new AchievementConfig()); }
  public static AchievementConfig GetRootAsAchievementConfig(ByteBuffer _bb, AchievementConfig obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public AchievementConfig __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int GroupId { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int Stage { get { int o = __p.__offset(8); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int TaskType { get { int o = __p.__offset(10); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int SortOrder { get { int o = __p.__offset(12); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int TaskParam { get { int o = __p.__offset(14); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string Description { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(16); }
  public int TargetValue { get { int o = __p.__offset(18); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int RewardId { get { int o = __p.__offset(20); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int RewardCount { get { int o = __p.__offset(22); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }

  public static Offset<AchievementConfig> CreateAchievementConfig(FlatBufferBuilder builder,
      int ID = 0,
      int GroupId = 0,
      int Stage = 0,
      int TaskType = 0,
      int SortOrder = 0,
      int TaskParam = 0,
      StringOffset DescriptionOffset = default(StringOffset),
      int TargetValue = 0,
      int RewardId = 0,
      int RewardCount = 0) {
    builder.StartObject(10);
    AchievementConfig.AddRewardCount(builder, RewardCount);
    AchievementConfig.AddRewardId(builder, RewardId);
    AchievementConfig.AddTargetValue(builder, TargetValue);
    AchievementConfig.AddDescription(builder, DescriptionOffset);
    AchievementConfig.AddTaskParam(builder, TaskParam);
    AchievementConfig.AddSortOrder(builder, SortOrder);
    AchievementConfig.AddTaskType(builder, TaskType);
    AchievementConfig.AddStage(builder, Stage);
    AchievementConfig.AddGroupId(builder, GroupId);
    AchievementConfig.AddID(builder, ID);
    return AchievementConfig.EndAchievementConfig(builder);
  }

  public static void StartAchievementConfig(FlatBufferBuilder builder) { builder.StartObject(10); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddGroupId(FlatBufferBuilder builder, int GroupId) { builder.AddInt(1, GroupId, 0); }
  public static void AddStage(FlatBufferBuilder builder, int Stage) { builder.AddInt(2, Stage, 0); }
  public static void AddTaskType(FlatBufferBuilder builder, int TaskType) { builder.AddInt(3, TaskType, 0); }
  public static void AddSortOrder(FlatBufferBuilder builder, int SortOrder) { builder.AddInt(4, SortOrder, 0); }
  public static void AddTaskParam(FlatBufferBuilder builder, int TaskParam) { builder.AddInt(5, TaskParam, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset DescriptionOffset) { builder.AddOffset(6, DescriptionOffset.Value, 0); }
  public static void AddTargetValue(FlatBufferBuilder builder, int TargetValue) { builder.AddInt(7, TargetValue, 0); }
  public static void AddRewardId(FlatBufferBuilder builder, int RewardId) { builder.AddInt(8, RewardId, 0); }
  public static void AddRewardCount(FlatBufferBuilder builder, int RewardCount) { builder.AddInt(9, RewardCount, 0); }
  public static Offset<AchievementConfig> EndAchievementConfig(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<AchievementConfig>(o);
  }
  public static void FinishAchievementConfigBuffer(FlatBufferBuilder builder, Offset<AchievementConfig> offset) { builder.Finish(offset.Value); }
};


}


#endif

