// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class DropPool : IFlatbufferObject
{
public enum eCrypt : int
{
 code = 487576105,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static DropPool GetRootAsDropPool(ByteBuffer _bb) { return GetRootAsDropPool(_bb, new DropPool()); }
  public static DropPool GetRootAsDropPool(ByteBuffer _bb, DropPool obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public DropPool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int PoolId { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string ItemIdsArray(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int ItemIdsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> ItemIdsValue;
 public FlatBufferArray<string>  ItemIds
 {
  get{
  if (ItemIdsValue == null)
  {
    ItemIdsValue = new FlatBufferArray<string>(this.ItemIdsArray, this.ItemIdsLength);
  }
  return ItemIdsValue;}
 }
  public string MinCountsArray(int j) { int o = __p.__offset(10); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int MinCountsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> MinCountsValue;
 public FlatBufferArray<string>  MinCounts
 {
  get{
  if (MinCountsValue == null)
  {
    MinCountsValue = new FlatBufferArray<string>(this.MinCountsArray, this.MinCountsLength);
  }
  return MinCountsValue;}
 }
  public string MaxCountsArray(int j) { int o = __p.__offset(12); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int MaxCountsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> MaxCountsValue;
 public FlatBufferArray<string>  MaxCounts
 {
  get{
  if (MaxCountsValue == null)
  {
    MaxCountsValue = new FlatBufferArray<string>(this.MaxCountsArray, this.MaxCountsLength);
  }
  return MaxCountsValue;}
 }
  public string WeightsArray(int j) { int o = __p.__offset(14); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int WeightsLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> WeightsValue;
 public FlatBufferArray<string>  Weights
 {
  get{
  if (WeightsValue == null)
  {
    WeightsValue = new FlatBufferArray<string>(this.WeightsArray, this.WeightsLength);
  }
  return WeightsValue;}
 }

  public static Offset<DropPool> CreateDropPool(FlatBufferBuilder builder,
      int ID = 0,
      int PoolId = 0,
      VectorOffset ItemIdsOffset = default(VectorOffset),
      VectorOffset MinCountsOffset = default(VectorOffset),
      VectorOffset MaxCountsOffset = default(VectorOffset),
      VectorOffset WeightsOffset = default(VectorOffset)) {
    builder.StartObject(6);
    DropPool.AddWeights(builder, WeightsOffset);
    DropPool.AddMaxCounts(builder, MaxCountsOffset);
    DropPool.AddMinCounts(builder, MinCountsOffset);
    DropPool.AddItemIds(builder, ItemIdsOffset);
    DropPool.AddPoolId(builder, PoolId);
    DropPool.AddID(builder, ID);
    return DropPool.EndDropPool(builder);
  }

  public static void StartDropPool(FlatBufferBuilder builder) { builder.StartObject(6); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddPoolId(FlatBufferBuilder builder, int PoolId) { builder.AddInt(1, PoolId, 0); }
  public static void AddItemIds(FlatBufferBuilder builder, VectorOffset ItemIdsOffset) { builder.AddOffset(2, ItemIdsOffset.Value, 0); }
  public static VectorOffset CreateItemIdsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartItemIdsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMinCounts(FlatBufferBuilder builder, VectorOffset MinCountsOffset) { builder.AddOffset(3, MinCountsOffset.Value, 0); }
  public static VectorOffset CreateMinCountsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMinCountsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddMaxCounts(FlatBufferBuilder builder, VectorOffset MaxCountsOffset) { builder.AddOffset(4, MaxCountsOffset.Value, 0); }
  public static VectorOffset CreateMaxCountsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartMaxCountsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddWeights(FlatBufferBuilder builder, VectorOffset WeightsOffset) { builder.AddOffset(5, WeightsOffset.Value, 0); }
  public static VectorOffset CreateWeightsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartWeightsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<DropPool> EndDropPool(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<DropPool>(o);
  }
  public static void FinishDropPoolBuffer(FlatBufferBuilder builder, Offset<DropPool> offset) { builder.Finish(offset.Value); }
};


}


#endif

