// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class ErrorCodeTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = 130819679,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ErrorCodeTable GetRootAsErrorCodeTable(ByteBuffer _bb) { return GetRootAsErrorCodeTable(_bb, new ErrorCodeTable()); }
  public static ErrorCodeTable GetRootAsErrorCodeTable(ByteBuffer _bb, ErrorCodeTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ErrorCodeTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string ErrorCode { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetErrorCodeBytes() { return __p.__vector_as_arraysegment(6); }
  public string CodeText { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetCodeTextBytes() { return __p.__vector_as_arraysegment(8); }
  public int CodeDisplay { get { int o = __p.__offset(10); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string Note { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetNoteBytes() { return __p.__vector_as_arraysegment(12); }

  public static Offset<ErrorCodeTable> CreateErrorCodeTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset ErrorCodeOffset = default(StringOffset),
      StringOffset CodeTextOffset = default(StringOffset),
      int CodeDisplay = 0,
      StringOffset NoteOffset = default(StringOffset)) {
    builder.StartObject(5);
    ErrorCodeTable.AddNote(builder, NoteOffset);
    ErrorCodeTable.AddCodeDisplay(builder, CodeDisplay);
    ErrorCodeTable.AddCodeText(builder, CodeTextOffset);
    ErrorCodeTable.AddErrorCode(builder, ErrorCodeOffset);
    ErrorCodeTable.AddID(builder, ID);
    return ErrorCodeTable.EndErrorCodeTable(builder);
  }

  public static void StartErrorCodeTable(FlatBufferBuilder builder) { builder.StartObject(5); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddErrorCode(FlatBufferBuilder builder, StringOffset ErrorCodeOffset) { builder.AddOffset(1, ErrorCodeOffset.Value, 0); }
  public static void AddCodeText(FlatBufferBuilder builder, StringOffset CodeTextOffset) { builder.AddOffset(2, CodeTextOffset.Value, 0); }
  public static void AddCodeDisplay(FlatBufferBuilder builder, int CodeDisplay) { builder.AddInt(3, CodeDisplay, 0); }
  public static void AddNote(FlatBufferBuilder builder, StringOffset NoteOffset) { builder.AddOffset(4, NoteOffset.Value, 0); }
  public static Offset<ErrorCodeTable> EndErrorCodeTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ErrorCodeTable>(o);
  }
  public static void FinishErrorCodeTableBuffer(FlatBufferBuilder builder, Offset<ErrorCodeTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

