// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class LexiconTable : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -160721668,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static LexiconTable GetRootAsLexiconTable(ByteBuffer _bb) { return GetRootAsLexiconTable(_bb, new LexiconTable()); }
  public static LexiconTable GetRootAsLexiconTable(ByteBuffer _bb, LexiconTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public LexiconTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int lexiconId { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string DisplayText { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetDisplayTextBytes() { return __p.__vector_as_arraysegment(8); }
  public int ThemePackId { get { int o = __p.__offset(10); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int CategoryTag { get { int o = __p.__offset(12); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public float Weight { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int EffectId { get { int o = __p.__offset(16); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }

  public static Offset<LexiconTable> CreateLexiconTable(FlatBufferBuilder builder,
      int ID = 0,
      int lexiconId = 0,
      StringOffset DisplayTextOffset = default(StringOffset),
      int ThemePackId = 0,
      int CategoryTag = 0,
      float Weight = 0.0f,
      int EffectId = 0) {
    builder.StartObject(7);
    LexiconTable.AddEffectId(builder, EffectId);
    LexiconTable.AddWeight(builder, Weight);
    LexiconTable.AddCategoryTag(builder, CategoryTag);
    LexiconTable.AddThemePackId(builder, ThemePackId);
    LexiconTable.AddDisplayText(builder, DisplayTextOffset);
    LexiconTable.AddLexiconId(builder, lexiconId);
    LexiconTable.AddID(builder, ID);
    return LexiconTable.EndLexiconTable(builder);
  }

  public static void StartLexiconTable(FlatBufferBuilder builder) { builder.StartObject(7); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddLexiconId(FlatBufferBuilder builder, int lexiconId) { builder.AddInt(1, lexiconId, 0); }
  public static void AddDisplayText(FlatBufferBuilder builder, StringOffset DisplayTextOffset) { builder.AddOffset(2, DisplayTextOffset.Value, 0); }
  public static void AddThemePackId(FlatBufferBuilder builder, int ThemePackId) { builder.AddInt(3, ThemePackId, 0); }
  public static void AddCategoryTag(FlatBufferBuilder builder, int CategoryTag) { builder.AddInt(4, CategoryTag, 0); }
  public static void AddWeight(FlatBufferBuilder builder, float Weight) { builder.AddFloat(5, Weight, 0.0f); }
  public static void AddEffectId(FlatBufferBuilder builder, int EffectId) { builder.AddInt(6, EffectId, 0); }
  public static Offset<LexiconTable> EndLexiconTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<LexiconTable>(o);
  }
  public static void FinishLexiconTableBuffer(FlatBufferBuilder builder, Offset<LexiconTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

