// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class Monster : IFlatbufferObject
{
public enum eCrypt : int
{
 code = -1159206884,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Monster GetRootAsMonster(ByteBuffer _bb) { return GetRootAsMonster(_bb, new Monster()); }
  public static Monster GetRootAsMonster(ByteBuffer _bb, Monster obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Monster __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int monsterId { get { int o = __p.__offset(6); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int type { get { int o = __p.__offset(8); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int CategoryTagArray(int j) { int o = __p.__offset(10); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int CategoryTagLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public ArraySegment<byte>? GetCategoryTagBytes() { return __p.__vector_as_arraysegment(10); }
 private FlatBufferArray<int> CategoryTagValue;
 public FlatBufferArray<int>  CategoryTag
 {
  get{
  if (CategoryTagValue == null)
  {
    CategoryTagValue = new FlatBufferArray<int>(this.CategoryTagArray, this.CategoryTagLength);
  }
  return CategoryTagValue;}
 }
  public int ThemePackId { get { int o = __p.__offset(12); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int randomKillPro { get { int o = __p.__offset(14); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int triggerMode { get { int o = __p.__offset(16); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string dropArray(int j) { int o = __p.__offset(18); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int dropLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> dropValue;
 public FlatBufferArray<string>  drop
 {
  get{
  if (dropValue == null)
  {
    dropValue = new FlatBufferArray<string>(this.dropArray, this.dropLength);
  }
  return dropValue;}
 }
  public string path { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetPathBytes() { return __p.__vector_as_arraysegment(20); }
  public string name { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(22); }
  public string beizhu { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetBeizhuBytes() { return __p.__vector_as_arraysegment(24); }
  public string describe { get { int o = __p.__offset(26); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetDescribeBytes() { return __p.__vector_as_arraysegment(26); }
  public string elementArray(int j) { int o = __p.__offset(28); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int elementLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> elementValue;
 public FlatBufferArray<string>  element
 {
  get{
  if (elementValue == null)
  {
    elementValue = new FlatBufferArray<string>(this.elementArray, this.elementLength);
  }
  return elementValue;}
 }
  public string elementNumArray(int j) { int o = __p.__offset(30); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int elementNumLength { get { int o = __p.__offset(30); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> elementNumValue;
 public FlatBufferArray<string>  elementNum
 {
  get{
  if (elementNumValue == null)
  {
    elementNumValue = new FlatBufferArray<string>(this.elementNumArray, this.elementNumLength);
  }
  return elementNumValue;}
 }
  public string ImmuneEffectArray(int j) { int o = __p.__offset(32); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : FlatBufferConstants.DefaultString; }
  public int ImmuneEffectLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
 private FlatBufferArray<string> ImmuneEffectValue;
 public FlatBufferArray<string>  ImmuneEffect
 {
  get{
  if (ImmuneEffectValue == null)
  {
    ImmuneEffectValue = new FlatBufferArray<string>(this.ImmuneEffectArray, this.ImmuneEffectLength);
  }
  return ImmuneEffectValue;}
 }
  public string pic { get { int o = __p.__offset(34); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetPicBytes() { return __p.__vector_as_arraysegment(34); }

  public static Offset<Monster> CreateMonster(FlatBufferBuilder builder,
      int ID = 0,
      int monsterId = 0,
      int type = 0,
      VectorOffset CategoryTagOffset = default(VectorOffset),
      int ThemePackId = 0,
      int randomKillPro = 0,
      int triggerMode = 0,
      VectorOffset dropOffset = default(VectorOffset),
      StringOffset pathOffset = default(StringOffset),
      StringOffset nameOffset = default(StringOffset),
      StringOffset beizhuOffset = default(StringOffset),
      StringOffset describeOffset = default(StringOffset),
      VectorOffset elementOffset = default(VectorOffset),
      VectorOffset elementNumOffset = default(VectorOffset),
      VectorOffset ImmuneEffectOffset = default(VectorOffset),
      StringOffset picOffset = default(StringOffset)) {
    builder.StartObject(16);
    Monster.AddPic(builder, picOffset);
    Monster.AddImmuneEffect(builder, ImmuneEffectOffset);
    Monster.AddElementNum(builder, elementNumOffset);
    Monster.AddElement(builder, elementOffset);
    Monster.AddDescribe(builder, describeOffset);
    Monster.AddBeizhu(builder, beizhuOffset);
    Monster.AddName(builder, nameOffset);
    Monster.AddPath(builder, pathOffset);
    Monster.AddDrop(builder, dropOffset);
    Monster.AddTriggerMode(builder, triggerMode);
    Monster.AddRandomKillPro(builder, randomKillPro);
    Monster.AddThemePackId(builder, ThemePackId);
    Monster.AddCategoryTag(builder, CategoryTagOffset);
    Monster.AddType(builder, type);
    Monster.AddMonsterId(builder, monsterId);
    Monster.AddID(builder, ID);
    return Monster.EndMonster(builder);
  }

  public static void StartMonster(FlatBufferBuilder builder) { builder.StartObject(16); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddMonsterId(FlatBufferBuilder builder, int monsterId) { builder.AddInt(1, monsterId, 0); }
  public static void AddType(FlatBufferBuilder builder, int type) { builder.AddInt(2, type, 0); }
  public static void AddCategoryTag(FlatBufferBuilder builder, VectorOffset CategoryTagOffset) { builder.AddOffset(3, CategoryTagOffset.Value, 0); }
  public static VectorOffset CreateCategoryTagVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static void StartCategoryTagVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddThemePackId(FlatBufferBuilder builder, int ThemePackId) { builder.AddInt(4, ThemePackId, 0); }
  public static void AddRandomKillPro(FlatBufferBuilder builder, int randomKillPro) { builder.AddInt(5, randomKillPro, 0); }
  public static void AddTriggerMode(FlatBufferBuilder builder, int triggerMode) { builder.AddInt(6, triggerMode, 0); }
  public static void AddDrop(FlatBufferBuilder builder, VectorOffset dropOffset) { builder.AddOffset(7, dropOffset.Value, 0); }
  public static VectorOffset CreateDropVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartDropVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPath(FlatBufferBuilder builder, StringOffset pathOffset) { builder.AddOffset(8, pathOffset.Value, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(9, nameOffset.Value, 0); }
  public static void AddBeizhu(FlatBufferBuilder builder, StringOffset beizhuOffset) { builder.AddOffset(10, beizhuOffset.Value, 0); }
  public static void AddDescribe(FlatBufferBuilder builder, StringOffset describeOffset) { builder.AddOffset(11, describeOffset.Value, 0); }
  public static void AddElement(FlatBufferBuilder builder, VectorOffset elementOffset) { builder.AddOffset(12, elementOffset.Value, 0); }
  public static VectorOffset CreateElementVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartElementVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddElementNum(FlatBufferBuilder builder, VectorOffset elementNumOffset) { builder.AddOffset(13, elementNumOffset.Value, 0); }
  public static VectorOffset CreateElementNumVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartElementNumVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddImmuneEffect(FlatBufferBuilder builder, VectorOffset ImmuneEffectOffset) { builder.AddOffset(14, ImmuneEffectOffset.Value, 0); }
  public static VectorOffset CreateImmuneEffectVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static void StartImmuneEffectVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPic(FlatBufferBuilder builder, StringOffset picOffset) { builder.AddOffset(15, picOffset.Value, 0); }
  public static Offset<Monster> EndMonster(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Monster>(o);
  }
  public static void FinishMonsterBuffer(FlatBufferBuilder builder, Offset<Monster> offset) { builder.Finish(offset.Value); }
};


}


#endif

