// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

#if USE_FB_TABLE

namespace ProtoTable
{

using global::System;
using global::FlatBuffers;

public class ShopTable : IFlatbufferObject
{
public enum eShopType : int
{
 ShopType_None = 0,
 normal = 1,
 holiday = 2,
 gift_package = 3,
 sevenday = 4,
 integral = 5,
 box = 6,
 reputation = 7,
};

public enum eCrypt : int
{
 code = 182865018,
};

  private Table __p = new Table();
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static ShopTable GetRootAsShopTable(ByteBuffer _bb) { return GetRootAsShopTable(_bb, new ShopTable()); }
  public static ShopTable GetRootAsShopTable(ByteBuffer _bb, ShopTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public ShopTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ID { get { int o = __p.__offset(4); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public string ShopName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetShopNameBytes() { return __p.__vector_as_arraysegment(6); }
  public ProtoTable.ShopTable.eShopType ShopType { get { int o = __p.__offset(8); return o != 0 ? (ProtoTable.ShopTable.eShopType)__p.bb.GetInt(o + __p.bb_pos) : ProtoTable.ShopTable.eShopType.ShopType_None; } }
  public string LatticeName { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : FlatBufferConstants.DefaultString; } }
  public ArraySegment<byte>? GetLatticeNameBytes() { return __p.__vector_as_arraysegment(10); }
  public int ItemID { get { int o = __p.__offset(12); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int ItemNumber { get { int o = __p.__offset(14); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int DropID { get { int o = __p.__offset(16); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int Rotate { get { int o = __p.__offset(18); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int PriceType { get { int o = __p.__offset(20); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int OldPrice { get { int o = __p.__offset(22); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int PurchaseDiscount { get { int o = __p.__offset(24); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int PurchaseNum { get { int o = __p.__offset(26); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int ActiveSet { get { int o = __p.__offset(28); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int Refresh { get { int o = __p.__offset(30); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int Unlock { get { int o = __p.__offset(32); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int Hide { get { int o = __p.__offset(34); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }
  public int RedPoint { get { int o = __p.__offset(36); return o != 0 ? (int)eCrypt.code^__p.bb.GetInt(o + __p.bb_pos) : 0; } }

  public static Offset<ShopTable> CreateShopTable(FlatBufferBuilder builder,
      int ID = 0,
      StringOffset ShopNameOffset = default(StringOffset),
      ProtoTable.ShopTable.eShopType ShopType = ProtoTable.ShopTable.eShopType.ShopType_None,
      StringOffset LatticeNameOffset = default(StringOffset),
      int ItemID = 0,
      int ItemNumber = 0,
      int DropID = 0,
      int Rotate = 0,
      int PriceType = 0,
      int OldPrice = 0,
      int PurchaseDiscount = 0,
      int PurchaseNum = 0,
      int ActiveSet = 0,
      int Refresh = 0,
      int Unlock = 0,
      int Hide = 0,
      int RedPoint = 0) {
    builder.StartObject(17);
    ShopTable.AddRedPoint(builder, RedPoint);
    ShopTable.AddHide(builder, Hide);
    ShopTable.AddUnlock(builder, Unlock);
    ShopTable.AddRefresh(builder, Refresh);
    ShopTable.AddActiveSet(builder, ActiveSet);
    ShopTable.AddPurchaseNum(builder, PurchaseNum);
    ShopTable.AddPurchaseDiscount(builder, PurchaseDiscount);
    ShopTable.AddOldPrice(builder, OldPrice);
    ShopTable.AddPriceType(builder, PriceType);
    ShopTable.AddRotate(builder, Rotate);
    ShopTable.AddDropID(builder, DropID);
    ShopTable.AddItemNumber(builder, ItemNumber);
    ShopTable.AddItemID(builder, ItemID);
    ShopTable.AddLatticeName(builder, LatticeNameOffset);
    ShopTable.AddShopType(builder, ShopType);
    ShopTable.AddShopName(builder, ShopNameOffset);
    ShopTable.AddID(builder, ID);
    return ShopTable.EndShopTable(builder);
  }

  public static void StartShopTable(FlatBufferBuilder builder) { builder.StartObject(17); }
  public static void AddID(FlatBufferBuilder builder, int ID) { builder.AddInt(0, ID, 0); }
  public static void AddShopName(FlatBufferBuilder builder, StringOffset ShopNameOffset) { builder.AddOffset(1, ShopNameOffset.Value, 0); }
  public static void AddShopType(FlatBufferBuilder builder, ProtoTable.ShopTable.eShopType ShopType) { builder.AddInt(2, (int)ShopType, 0); }
  public static void AddLatticeName(FlatBufferBuilder builder, StringOffset LatticeNameOffset) { builder.AddOffset(3, LatticeNameOffset.Value, 0); }
  public static void AddItemID(FlatBufferBuilder builder, int ItemID) { builder.AddInt(4, ItemID, 0); }
  public static void AddItemNumber(FlatBufferBuilder builder, int ItemNumber) { builder.AddInt(5, ItemNumber, 0); }
  public static void AddDropID(FlatBufferBuilder builder, int DropID) { builder.AddInt(6, DropID, 0); }
  public static void AddRotate(FlatBufferBuilder builder, int Rotate) { builder.AddInt(7, Rotate, 0); }
  public static void AddPriceType(FlatBufferBuilder builder, int PriceType) { builder.AddInt(8, PriceType, 0); }
  public static void AddOldPrice(FlatBufferBuilder builder, int OldPrice) { builder.AddInt(9, OldPrice, 0); }
  public static void AddPurchaseDiscount(FlatBufferBuilder builder, int PurchaseDiscount) { builder.AddInt(10, PurchaseDiscount, 0); }
  public static void AddPurchaseNum(FlatBufferBuilder builder, int PurchaseNum) { builder.AddInt(11, PurchaseNum, 0); }
  public static void AddActiveSet(FlatBufferBuilder builder, int ActiveSet) { builder.AddInt(12, ActiveSet, 0); }
  public static void AddRefresh(FlatBufferBuilder builder, int Refresh) { builder.AddInt(13, Refresh, 0); }
  public static void AddUnlock(FlatBufferBuilder builder, int Unlock) { builder.AddInt(14, Unlock, 0); }
  public static void AddHide(FlatBufferBuilder builder, int Hide) { builder.AddInt(15, Hide, 0); }
  public static void AddRedPoint(FlatBufferBuilder builder, int RedPoint) { builder.AddInt(16, RedPoint, 0); }
  public static Offset<ShopTable> EndShopTable(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<ShopTable>(o);
  }
  public static void FinishShopTableBuffer(FlatBufferBuilder builder, Offset<ShopTable> offset) { builder.Finish(offset.Value); }
};


}


#endif

